### ISSUE TITLE
Consider changing NAME to DB_NAME

### ISSUE THREAD

**Issue by sfc-gh-hachouraria** [Snowflake-Labs/django-snowflake#65]
It isn't immediately obvious when filling the `DATABASES` config section on what the value of `NAME` should be. The example helps but the key name by itself (as `NAME`) is implicit in requesting a database name.

Could this config key name be changed from `NAME` to `DB_NAME` or `DATABASE`? This would align it with the other explicit key names.

**Comment by timgraham** [comment]
`NAME` is [what Django uses](https://docs.djangoproject.com/en/dev/ref/settings/#databases). I don't think it's a good idea to name it differently in this backend.

**Comment by sfc-gh-hachouraria** [comment]
Thank you and apologies for the noise in that case, I should have compared against other existing configs.
