### ISSUE TITLE
Datetime should be Timestamp_ntz

### ISSUE THREAD

**Issue by Ajith-Raja** [Snowflake-Labs/django-snowflake#73]
https://github.com/Snowflake-Labs/django-snowflake/blob/25c603482b39109509eb2a549672cd9404e5dc6c/django_snowflake/base.py#L32

timestamp_ltz is converting the time and inserting, whereas timestamp_ntz inserts the time as it is, so better use timestamp_ntz. Is there any reason in using timestamp_ltz.

**Comment by Ajith-Raja** [comment]
> 

Yes is is something like converting the passed datetime to other timezone when inserting

**Comment by Ajith-Raja** [comment]
so we are dropping the column and creating with timestamp_ntz manually

**Comment by timgraham** [comment]
If you think there's a bug, please include steps to reproduce it.

Closing as invalid.
