### ISSUE TITLE
Persistent DB connection (a la `CONN_MAX_AGE`)

### ISSUE THREAD

**Issue by sim-dt** [Snowflake-Labs/django-snowflake#74]
Does `django-snowflake` support a persistent DB connection, in the same vein as Django's usual CONN_MAX_AGE?

I tried setting `client_session_keep_alive`, but from what I can glean from the logs the app is still creating and closing a new Snowflake connection for every request.

**Comment by timgraham** [comment]
Did you also set `CONN_MAX_AGE`?

**Comment by sim-dt** [comment]
No, can I set that with `django-snowflake`? 😅

**Comment by sim-dt** [comment]
Okay, I set `CONN_MAX_AGE` and it works. :)

Might be worth adding both of these options to your README example.

Thanks for your help!

**Comment by timgraham** [comment]
I proposed documentation in #78. Look okay?

**Comment by sim-dt** [comment]
Great, looks good. Thanks!
