### ISSUE TITLE
Receiving 'Error detecting the version of libcrypto' when connecting to Django

### ISSUE THREAD

**Issue by msalbego93** [Snowflake-Labs/django-snowflake#75]
Python version= 3.8.17
I am running Django 4.1.10  and django-snowflake =4.1b1. After setting my settings.py DATABASES with the right credentials and running  `python manage.py runserver` I get the following error :

>     raise LibraryNotFoundError('Error detecting the version of libcrypto')
>     oscrypto.errors.LibraryNotFoundError: Error detecting the version of libcrypto

my pip freeze looks like this

`asgiref==3.7.2
asn1crypto==1.5.1
backports.zoneinfo==0.2.1
binutils==0.2.dev0
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
cryptography==41.0.3
Django==4.1.10
django-snowflake==4.1b1
filelock==3.12.2
idna==3.4
oscrypto==1.3.0
packaging==23.1
platformdirs==3.8.1
pycparser==2.21
pycryptodomex==3.18.0
PyJWT==2.8.0
pyOpenSSL==23.2.0
pytz==2023.3
requests==2.31.0
snowflake-connector-python==3.1.0
sortedcontainers==2.4.0
sqlparse==0.4.4
tomlkit==0.12.1
typing_extensions==4.7.1
urllib3==1.26.16`

what should be the cause of this?

Edit: Also tested with pyOpenSSL (23.1.1, 23.1.0, 22.0.0)

Thank you

**Comment by timgraham** [comment]
The error doesn't come from django-snowflake. A web search for the error message led to https://github.com/wbond/oscrypto/issues/75.
