### ISSUE TITLE
Slow performance

### ISSUE THREAD

**Issue by daniel-albuixech** [Snowflake-Labs/django-snowflake#80]
Hello all,

Recently I discovered this Snowflake backend for Django so let me thank you the effort because it's something I've been waiting for months.

The reason of this issue is because I've been playing with it and I experience slow performance. I would like to know if others are facing similar issues and if there are any recommended solutions or workarounds.

I did two tests with the following environments:

```
python                     3.11.3
Django                     4.2.7
django-snowflake           4.2b1
```
and
```
python                     3.10.4
Django                     4.2.1
django-snowflake           4.2b1
```

In both cases I followed the same steps, I created a fresh new conda enviroment and I configured the **Django admin-site** to use an small table (10 records) where to perform CRUD operations. Every operation takes around 10 seconds. It doesn't matter if I list all the records of the table or if I try to update a single record... it always takes 9s, 10s, 11s approximately.

Another comparison that I did was using `snowflake-sqlalchemy` package, against the same table, and there I didn't have any performance issue.

I would appreciate any guidance or recommendation.

Thanks in advance

**Comment by timgraham** [comment]
Hi Daniel, please let me know if you have any further profiling data or suggestions. Thanks.

**Comment by eddy-oj** [comment]
I also find Snowflake too slow as an app backend but as a data warehouse it is excellent and works with django for background ETL tasks.

With native connection pooling in Django 5.1, are there plans to allow this in django-snowflake? I presume it will help speed it up slightly

**Comment by timgraham** [comment]
Django leverages libraries like psycopg_pool and python-oracledb to provide connection pooling. As far as I see, Snowflake Connector for Python doesn't provide support for connection pooling. Incidentally, I found a Snowflake connector from devart that [supports connection pooling](https://docs.devart.com/python/snowflake/connection-pooling.htm). 

[An initial attempt at connection pooling](https://github.com/Snowflake-Labs/django-snowflake/pull/106) was opened and closed without comment from the author.
